#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.logourl = "https://upload.wikimedia.org/wikipedia/commons/1/1e/YunoHost_logo.png"
   