#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret_key --value=$secret_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=admin_mail --value=$admin_mail

timezone="$(cat /etc/timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir/web"
touch "$install_dir/web/uwsgi.sock" 
touch "$install_dir/web/uwsgi-stats.sock" 

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="uwsgi-indico.ini" --destination="$install_dir/uwsgi-indico.ini"
ynh_config_add --template="indico.conf" --destination="$install_dir/.indico.conf"
ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
    python3 -m venv $install_dir/venv
    ynh_hide_warnings $install_dir/venv/bin/pip install --upgrade pip setuptools wheel uwsgi
    ynh_hide_warnings $install_dir/venv/bin/pip install indico
    ynh_hide_warnings $install_dir/venv/bin/pip install python-dotenv
    #indico db prepare
popd

chown -R "$app:www-data" "$install_dir" 

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-celery" --template="$app-celery.service"
ynh_config_add_systemd --service="$app-uwsgi" --template="$app-uwsgi.service"

yunohost service add "$app-celery" --description="Celery for indico" --log="/var/log/$app/$app-celery"
yunohost service add "$app-uwsgi" --description="uwsgi for indico" --log="/var/log/$app/$app-uwsgi"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-uwsgi" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
