#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret_key --value=$secret_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=admin_mail --value=$admin_mail

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=redis_db --value=$redis_db
redis_lock "redis_db" 

celery_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=celery_db --value=$celery_db
redis_unlock "redis_db"

ynh_app_setting_set --key=logourl --value=$logourl

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir/web" "$install_dir/archive"  "$install_dir/cache"  "$install_dir/log"  "$install_dir/tmp"  "$install_dir/etc" "$install_dir/.uv" "$install_dir/.python_runtime" "$install_dir/.uv_cache"
ynh_setup_source --dest_dir="$install_dir/.uv" --source_id="uv"
chmod +x "$install_dir/.uv/uv"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="indico.conf" --destination="$install_dir/etc/indico.conf"
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="logging.yaml" --destination="$install_dir/logging.yaml"
ynh_config_add --template="indico.wsgi" --destination="$install_dir/web/indico.wsgi"

ynh_psql_db_shell $db_name <<< "CREATE EXTENSION unaccent;"
ynh_psql_db_shell $db_name <<< "CREATE EXTENSION pg_trgm;"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Preparing UV..."
    export PATH="$install_dir/.uv:$PATH"
    export UV_PYTHON_INSTALL_DIR="$install_dir/.python_runtime"
    export UV_CACHE_DIR="$install_dir/.uv_cache"
    echo "PATH=$install_dir/bin:\$PATH" >> $install_dir/.bashrc 
    echo "UV_PYTHON_INSTALL_DIR=$install_dir/.python_runtime" >> $install_dir/.bashrc 
    echo "UV_CACHE_DIR=$install_dir/.uv_cache" >> $install_dir/.bashrc
    
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
    ynh_exec_as_app uv venv "$install_dir/.venv" --python 3.12
    echo "source $install_dir/.venv/bin/activate" >> $install_dir/.bashrc
    ynh_exec_as_app uv pip install --upgrade pip setuptools wheel granian 2>&1
    ynh_exec_as_app uv pip install indico 2>&1
    ynh_exec_as_app uv pip install python-dotenv 2>&1
    ynh_exec_as_app uv pip install indico-plugins 2>&1
    mkdir -p /var/log/$app
    touch /var/log/$app/$app-celery.log
    touch /var/log/$app/$app-granian.log
    ln -s etc/indico.conf .indico.conf
# I don't know why, but without this symlink the install produces a site without styles
    ln -s $install_dir/.venv/lib/python$py_vshort/site-packages/indico/web/static $install_dir/web/static
    ln -s web/indico.wsgi wsgi.py
    ynh_exec_as_app uv indico setup create-symlinks $install_dir  2>&1
    ynh_exec_as_app uv indico setup create-logging-config $install_dir/etc  2>&1
    ynh_exec_as_app uv indico db prepare  2>&1
    ynh_exec_as_app uv indico db --all-plugins upgrade  2>&1
popd

chown -R "$app:www-data" "$install_dir" 
chown -R "$app:www-data" "/var/log/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-celery" --template="indico-celery.service"
ynh_config_add_systemd --service="$app-granian" --template="indico-granian.service"

yunohost service add "$app-celery" --description="Celery for indico" --log="/var/log/$app/$app-celery.log"
yunohost service add "$app-granian" --description="granian for indico" --log="/var/log/$app/$app-granian.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-granian" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
