#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

yunohost service remove "$app-celery"
yunohost service remove "$app-granian"

ynh_config_remove_systemd "$app-celery" 
ynh_config_remove_systemd "$app-granian"

ynh_config_remove_nginx

ynh_redis_remove_db "$redis_db"
ynh_redis_remove_db "$celery_db"

uninstall_python $py_version

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
