#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [[ "$mail_user" != "noreply" && "$mail_user" != "contact" ]]; then
    mail_user="noreply"
    ynh_app_setting_set --key=mail_user --value="noreply" 
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-celery" --action="stop"
ynh_systemctl --service="$app-uwsgi" --action="stop"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

logourl=$(ynh_app_setting_get --key=logourl)

ynh_config_add --template="uwsgi-indico.ini" --destination="$install_dir/uwsgi-indico.ini"
ynh_config_add --template="indico.conf" --destination="$install_dir/etc/indico.conf"
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="logging.yaml" --destination="$install_dir/logging.yaml"
ynh_config_add --template="indico.wsgi" --destination="$install_dir/web/indico.wsgi"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

check_python

pushd $install_dir
    source "$install_dir/.venv/bin/activate"
    pip install -U indico 2>&1
    pip install -U indico-plugins 2>&1
    indico db upgrade 2>&1
    indico db --all-plugins upgrade 2>&1
    deactivate
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-celery" --template="indico-celery.service"
ynh_config_add_systemd --service="$app-uwsgi" --template="indico-uwsgi.service"

yunohost service add "$app-celery" --description="Celery for indico" --log="/var/log/$app/$app-celery.log"
yunohost service add "$app-uwsgi" --description="uwsgi for indico" --log="/var/log/$app/$app-uwsgi.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-celery" --action="start"
ynh_systemctl --service="$app-uwsgi" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
